version: '3'

services:
  backend-payme:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
#  frontend-payme:
#    image: frontend-payme
#    ports:
#      - "3000:3000"
#    depends_on:
#      - backend-payme
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    depends_on:
      - redis_queue
    volumes:
      - mongodb-data:/data/db
  redis_queue:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data/redis



volumes:
  mongodb-data:
  redis-data: